[package]
name = "rust_lib_pumpkin_app"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
pumpkin = { path = "Pumpkin/pumpkin" }
