// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PumpkinServer>>
abstract class PumpkinServer implements RustOpaqueInterface {
  Future<String> getInfo();

  Future<int> getPlayerCount();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<PumpkinServer> newInstance({required String appDir}) =>
      RustLib.instance.api.crateApiSimplePumpkinServerNew(appDir: appDir);

  Future<void> runCommand({required String command});

  Future<void> start();

  Future<void> stop();
}
